/* Generated by Yosys 0.13+15 (git sha1 bc027b2ca, gcc 11.3.0-1ubuntu1~22.04 -fPIC -Os) */

module des(clock, enable, load, din, dout);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire \DATA.din[0] ;
  wire \DATA.din[10] ;
  wire \DATA.din[11] ;
  wire \DATA.din[12] ;
  wire \DATA.din[13] ;
  wire \DATA.din[14] ;
  wire \DATA.din[15] ;
  wire \DATA.din[16] ;
  wire \DATA.din[17] ;
  wire \DATA.din[18] ;
  wire \DATA.din[19] ;
  wire \DATA.din[1] ;
  wire \DATA.din[20] ;
  wire \DATA.din[21] ;
  wire \DATA.din[22] ;
  wire \DATA.din[23] ;
  wire \DATA.din[24] ;
  wire \DATA.din[25] ;
  wire \DATA.din[26] ;
  wire \DATA.din[27] ;
  wire \DATA.din[28] ;
  wire \DATA.din[29] ;
  wire \DATA.din[2] ;
  wire \DATA.din[30] ;
  wire \DATA.din[31] ;
  wire \DATA.din[3] ;
  wire \DATA.din[4] ;
  wire \DATA.din[5] ;
  wire \DATA.din[6] ;
  wire \DATA.din[7] ;
  wire \DATA.din[8] ;
  wire \DATA.din[9] ;
  wire \DEMUX16X4.d_in ;
  input clock;
  input din;
  output [31:0] dout;
  input enable;
  input load;
  BUFx3_ASAP7_75t_SL _171_ (
    .A(_032_),
    .Y(_107_)
  );
  BUFx3_ASAP7_75t_SL _172_ (
    .A(_066_),
    .Y(_108_)
  );
  AND2x2_ASAP7_75t_SL _173_ (
    .A(_107_),
    .B(_108_),
    .Y(_109_)
  );
  BUFx6f_ASAP7_75t_SL _174_ (
    .A(_033_),
    .Y(_110_)
  );
  INVx1_ASAP7_75t_SL _175_ (
    .A(_110_),
    .Y(_111_)
  );
  AND3x1_ASAP7_75t_SL _176_ (
    .A(_067_),
    .B(_068_),
    .C(_111_),
    .Y(_112_)
  );
  NAND2x1_ASAP7_75t_SL _177_ (
    .A(_109_),
    .B(_112_),
    .Y(_001_)
  );
  INVx1_ASAP7_75t_SL _178_ (
    .A(_068_),
    .Y(_113_)
  );
  AND3x1_ASAP7_75t_SL _179_ (
    .A(_067_),
    .B(_113_),
    .C(_110_),
    .Y(_114_)
  );
  NAND2x1_ASAP7_75t_SL _180_ (
    .A(_109_),
    .B(_114_),
    .Y(_002_)
  );
  AND3x1_ASAP7_75t_SL _181_ (
    .A(_067_),
    .B(_113_),
    .C(_111_),
    .Y(_115_)
  );
  NAND2x1_ASAP7_75t_SL _182_ (
    .A(_109_),
    .B(_115_),
    .Y(_003_)
  );
  INVx1_ASAP7_75t_SL _183_ (
    .A(_067_),
    .Y(_116_)
  );
  AND3x1_ASAP7_75t_SL _184_ (
    .A(_116_),
    .B(_068_),
    .C(_110_),
    .Y(_117_)
  );
  NAND2x1_ASAP7_75t_SL _185_ (
    .A(_109_),
    .B(_117_),
    .Y(_004_)
  );
  NAND2x1_ASAP7_75t_SL _186_ (
    .A(_107_),
    .B(_108_),
    .Y(_118_)
  );
  OR3x1_ASAP7_75t_SL _187_ (
    .A(_067_),
    .B(_113_),
    .C(_110_),
    .Y(_119_)
  );
  OR2x2_ASAP7_75t_SL _188_ (
    .A(_118_),
    .B(_119_),
    .Y(_005_)
  );
  AND3x1_ASAP7_75t_SL _189_ (
    .A(_116_),
    .B(_113_),
    .C(_110_),
    .Y(_120_)
  );
  NAND2x1_ASAP7_75t_SL _190_ (
    .A(_109_),
    .B(_120_),
    .Y(_006_)
  );
  OR3x2_ASAP7_75t_SL _191_ (
    .A(_067_),
    .B(_068_),
    .C(_110_),
    .Y(_121_)
  );
  OR2x2_ASAP7_75t_SL _192_ (
    .A(_118_),
    .B(_121_),
    .Y(_007_)
  );
  INVx1_ASAP7_75t_SL _193_ (
    .A(_108_),
    .Y(_122_)
  );
  AND2x2_ASAP7_75t_SL _194_ (
    .A(_107_),
    .B(_122_),
    .Y(_123_)
  );
  AND3x1_ASAP7_75t_SL _195_ (
    .A(_067_),
    .B(_068_),
    .C(_110_),
    .Y(_124_)
  );
  NAND2x1_ASAP7_75t_SL _196_ (
    .A(_123_),
    .B(_124_),
    .Y(_008_)
  );
  NAND2x1_ASAP7_75t_SL _197_ (
    .A(_112_),
    .B(_123_),
    .Y(_009_)
  );
  NAND2x1_ASAP7_75t_SL _198_ (
    .A(_114_),
    .B(_123_),
    .Y(_010_)
  );
  NAND2x1_ASAP7_75t_SL _199_ (
    .A(_115_),
    .B(_123_),
    .Y(_011_)
  );
  NAND2x1_ASAP7_75t_SL _200_ (
    .A(_117_),
    .B(_123_),
    .Y(_012_)
  );
  INVx1_ASAP7_75t_SL _201_ (
    .A(_107_),
    .Y(_125_)
  );
  OR3x1_ASAP7_75t_SL _202_ (
    .A(_125_),
    .B(_108_),
    .C(_119_),
    .Y(_013_)
  );
  NAND2x1_ASAP7_75t_SL _203_ (
    .A(_120_),
    .B(_123_),
    .Y(_014_)
  );
  OR3x1_ASAP7_75t_SL _204_ (
    .A(_125_),
    .B(_108_),
    .C(_121_),
    .Y(_015_)
  );
  AND2x2_ASAP7_75t_SL _205_ (
    .A(_125_),
    .B(_108_),
    .Y(_126_)
  );
  NAND2x1_ASAP7_75t_SL _206_ (
    .A(_124_),
    .B(_126_),
    .Y(_016_)
  );
  NAND2x1_ASAP7_75t_SL _207_ (
    .A(_112_),
    .B(_126_),
    .Y(_017_)
  );
  NAND2x1_ASAP7_75t_SL _208_ (
    .A(_114_),
    .B(_126_),
    .Y(_018_)
  );
  NAND2x1_ASAP7_75t_SL _209_ (
    .A(_115_),
    .B(_126_),
    .Y(_019_)
  );
  NAND2x1_ASAP7_75t_SL _210_ (
    .A(_117_),
    .B(_126_),
    .Y(_020_)
  );
  OR3x1_ASAP7_75t_SL _211_ (
    .A(_107_),
    .B(_122_),
    .C(_119_),
    .Y(_021_)
  );
  NAND2x1_ASAP7_75t_SL _212_ (
    .A(_120_),
    .B(_126_),
    .Y(_022_)
  );
  OR3x1_ASAP7_75t_SL _213_ (
    .A(_107_),
    .B(_122_),
    .C(_121_),
    .Y(_023_)
  );
  NOR2x1_ASAP7_75t_SL _214_ (
    .A(_107_),
    .B(_108_),
    .Y(_127_)
  );
  NAND2x1_ASAP7_75t_SL _215_ (
    .A(_124_),
    .B(_127_),
    .Y(_024_)
  );
  NAND2x1_ASAP7_75t_SL _216_ (
    .A(_112_),
    .B(_127_),
    .Y(_025_)
  );
  NAND2x1_ASAP7_75t_SL _217_ (
    .A(_114_),
    .B(_127_),
    .Y(_026_)
  );
  NAND2x1_ASAP7_75t_SL _218_ (
    .A(_115_),
    .B(_127_),
    .Y(_027_)
  );
  NAND2x1_ASAP7_75t_SL _219_ (
    .A(_117_),
    .B(_127_),
    .Y(_028_)
  );
  OR3x1_ASAP7_75t_SL _220_ (
    .A(_107_),
    .B(_108_),
    .C(_119_),
    .Y(_029_)
  );
  NAND2x1_ASAP7_75t_SL _221_ (
    .A(_120_),
    .B(_127_),
    .Y(_030_)
  );
  OR3x2_ASAP7_75t_SL _222_ (
    .A(_107_),
    .B(_108_),
    .C(_121_),
    .Y(_031_)
  );
  NAND2x1_ASAP7_75t_SL _223_ (
    .A(_109_),
    .B(_124_),
    .Y(_000_)
  );
  AND2x2_ASAP7_75t_SL _224_ (
    .A(din),
    .B(enable),
    .Y(\DEMUX16X4.d_in )
  );
  INVx1_ASAP7_75t_SL _225_ (
    .A(clock),
    .Y(_069_)
  );
  INVx1_ASAP7_75t_SL _226_ (
    .A(_034_),
    .Y(dout[31])
  );
  INVx1_ASAP7_75t_SL _227_ (
    .A(_035_),
    .Y(dout[30])
  );
  INVx1_ASAP7_75t_SL _228_ (
    .A(_036_),
    .Y(dout[29])
  );
  INVx1_ASAP7_75t_SL _229_ (
    .A(_037_),
    .Y(dout[28])
  );
  INVx1_ASAP7_75t_SL _230_ (
    .A(_038_),
    .Y(dout[27])
  );
  INVx1_ASAP7_75t_SL _231_ (
    .A(_039_),
    .Y(dout[26])
  );
  INVx1_ASAP7_75t_SL _232_ (
    .A(_040_),
    .Y(dout[25])
  );
  INVx1_ASAP7_75t_SL _233_ (
    .A(_041_),
    .Y(dout[24])
  );
  INVx1_ASAP7_75t_SL _234_ (
    .A(_042_),
    .Y(dout[23])
  );
  INVx1_ASAP7_75t_SL _235_ (
    .A(_043_),
    .Y(dout[22])
  );
  INVx1_ASAP7_75t_SL _236_ (
    .A(_044_),
    .Y(dout[21])
  );
  INVx1_ASAP7_75t_SL _237_ (
    .A(_045_),
    .Y(dout[20])
  );
  INVx1_ASAP7_75t_SL _238_ (
    .A(_046_),
    .Y(dout[19])
  );
  INVx1_ASAP7_75t_SL _239_ (
    .A(_047_),
    .Y(dout[18])
  );
  INVx1_ASAP7_75t_SL _240_ (
    .A(_048_),
    .Y(dout[17])
  );
  INVx1_ASAP7_75t_SL _241_ (
    .A(_049_),
    .Y(dout[16])
  );
  INVx1_ASAP7_75t_SL _242_ (
    .A(_050_),
    .Y(dout[15])
  );
  INVx1_ASAP7_75t_SL _243_ (
    .A(_051_),
    .Y(dout[14])
  );
  INVx1_ASAP7_75t_SL _244_ (
    .A(_052_),
    .Y(dout[13])
  );
  INVx1_ASAP7_75t_SL _245_ (
    .A(_053_),
    .Y(dout[12])
  );
  INVx1_ASAP7_75t_SL _246_ (
    .A(_054_),
    .Y(dout[11])
  );
  INVx1_ASAP7_75t_SL _247_ (
    .A(_055_),
    .Y(dout[10])
  );
  INVx1_ASAP7_75t_SL _248_ (
    .A(_056_),
    .Y(dout[9])
  );
  INVx1_ASAP7_75t_SL _249_ (
    .A(_057_),
    .Y(dout[8])
  );
  INVx1_ASAP7_75t_SL _250_ (
    .A(_058_),
    .Y(dout[7])
  );
  INVx1_ASAP7_75t_SL _251_ (
    .A(_059_),
    .Y(dout[6])
  );
  INVx1_ASAP7_75t_SL _252_ (
    .A(_060_),
    .Y(dout[5])
  );
  INVx1_ASAP7_75t_SL _253_ (
    .A(_061_),
    .Y(dout[4])
  );
  INVx1_ASAP7_75t_SL _254_ (
    .A(_062_),
    .Y(dout[3])
  );
  INVx1_ASAP7_75t_SL _255_ (
    .A(_063_),
    .Y(dout[2])
  );
  INVx1_ASAP7_75t_SL _256_ (
    .A(_064_),
    .Y(dout[1])
  );
  INVx1_ASAP7_75t_SL _257_ (
    .A(_065_),
    .Y(dout[0])
  );
  INVx1_ASAP7_75t_SL _258_ (
    .A(load),
    .Y(_128_)
  );
  BUFx2_ASAP7_75t_SL _259_ (
    .A(_128_),
    .Y(_129_)
  );
  AND2x2_ASAP7_75t_SL _260_ (
    .A(\DATA.din[0] ),
    .B(load),
    .Y(_130_)
  );
  AO21x1_ASAP7_75t_SL _261_ (
    .A1(dout[0]),
    .A2(_129_),
    .B(_130_),
    .Y(_075_)
  );
  BUFx2_ASAP7_75t_SL _262_ (
    .A(load),
    .Y(_131_)
  );
  AND2x2_ASAP7_75t_SL _263_ (
    .A(_131_),
    .B(\DATA.din[1] ),
    .Y(_132_)
  );
  AO21x1_ASAP7_75t_SL _264_ (
    .A1(dout[1]),
    .A2(_129_),
    .B(_132_),
    .Y(_076_)
  );
  AND2x2_ASAP7_75t_SL _265_ (
    .A(_131_),
    .B(\DATA.din[2] ),
    .Y(_133_)
  );
  AO21x1_ASAP7_75t_SL _266_ (
    .A1(dout[2]),
    .A2(_129_),
    .B(_133_),
    .Y(_077_)
  );
  AND2x2_ASAP7_75t_SL _267_ (
    .A(_131_),
    .B(\DATA.din[3] ),
    .Y(_134_)
  );
  AO21x1_ASAP7_75t_SL _268_ (
    .A1(dout[3]),
    .A2(_129_),
    .B(_134_),
    .Y(_078_)
  );
  AND2x2_ASAP7_75t_SL _269_ (
    .A(_131_),
    .B(\DATA.din[4] ),
    .Y(_135_)
  );
  AO21x1_ASAP7_75t_SL _270_ (
    .A1(dout[4]),
    .A2(_129_),
    .B(_135_),
    .Y(_079_)
  );
  AND2x2_ASAP7_75t_SL _271_ (
    .A(_131_),
    .B(\DATA.din[5] ),
    .Y(_136_)
  );
  AO21x1_ASAP7_75t_SL _272_ (
    .A1(dout[5]),
    .A2(_129_),
    .B(_136_),
    .Y(_080_)
  );
  AND2x2_ASAP7_75t_SL _273_ (
    .A(_131_),
    .B(\DATA.din[6] ),
    .Y(_137_)
  );
  AO21x1_ASAP7_75t_SL _274_ (
    .A1(dout[6]),
    .A2(_129_),
    .B(_137_),
    .Y(_081_)
  );
  BUFx2_ASAP7_75t_SL _275_ (
    .A(_128_),
    .Y(_138_)
  );
  AND2x2_ASAP7_75t_SL _276_ (
    .A(_131_),
    .B(\DATA.din[7] ),
    .Y(_139_)
  );
  AO21x1_ASAP7_75t_SL _277_ (
    .A1(dout[7]),
    .A2(_138_),
    .B(_139_),
    .Y(_082_)
  );
  AND2x2_ASAP7_75t_SL _278_ (
    .A(_131_),
    .B(\DATA.din[8] ),
    .Y(_140_)
  );
  AO21x1_ASAP7_75t_SL _279_ (
    .A1(dout[8]),
    .A2(_138_),
    .B(_140_),
    .Y(_083_)
  );
  AND2x2_ASAP7_75t_SL _280_ (
    .A(_131_),
    .B(\DATA.din[9] ),
    .Y(_141_)
  );
  AO21x1_ASAP7_75t_SL _281_ (
    .A1(dout[9]),
    .A2(_138_),
    .B(_141_),
    .Y(_084_)
  );
  AND2x2_ASAP7_75t_SL _282_ (
    .A(_131_),
    .B(\DATA.din[10] ),
    .Y(_142_)
  );
  AO21x1_ASAP7_75t_SL _283_ (
    .A1(dout[10]),
    .A2(_138_),
    .B(_142_),
    .Y(_085_)
  );
  BUFx2_ASAP7_75t_SL _284_ (
    .A(load),
    .Y(_143_)
  );
  AND2x2_ASAP7_75t_SL _285_ (
    .A(_143_),
    .B(\DATA.din[11] ),
    .Y(_144_)
  );
  AO21x1_ASAP7_75t_SL _286_ (
    .A1(dout[11]),
    .A2(_138_),
    .B(_144_),
    .Y(_086_)
  );
  AND2x2_ASAP7_75t_SL _287_ (
    .A(_143_),
    .B(\DATA.din[12] ),
    .Y(_145_)
  );
  AO21x1_ASAP7_75t_SL _288_ (
    .A1(dout[12]),
    .A2(_138_),
    .B(_145_),
    .Y(_087_)
  );
  AND2x2_ASAP7_75t_SL _289_ (
    .A(_143_),
    .B(\DATA.din[13] ),
    .Y(_146_)
  );
  AO21x1_ASAP7_75t_SL _290_ (
    .A1(dout[13]),
    .A2(_138_),
    .B(_146_),
    .Y(_088_)
  );
  AND2x2_ASAP7_75t_SL _291_ (
    .A(_143_),
    .B(\DATA.din[14] ),
    .Y(_147_)
  );
  AO21x1_ASAP7_75t_SL _292_ (
    .A1(dout[14]),
    .A2(_138_),
    .B(_147_),
    .Y(_089_)
  );
  AND2x2_ASAP7_75t_SL _293_ (
    .A(_143_),
    .B(\DATA.din[15] ),
    .Y(_148_)
  );
  AO21x1_ASAP7_75t_SL _294_ (
    .A1(dout[15]),
    .A2(_138_),
    .B(_148_),
    .Y(_090_)
  );
  AND2x2_ASAP7_75t_SL _295_ (
    .A(_143_),
    .B(\DATA.din[16] ),
    .Y(_149_)
  );
  AO21x1_ASAP7_75t_SL _296_ (
    .A1(dout[16]),
    .A2(_138_),
    .B(_149_),
    .Y(_091_)
  );
  BUFx2_ASAP7_75t_SL _297_ (
    .A(_128_),
    .Y(_150_)
  );
  AND2x2_ASAP7_75t_SL _298_ (
    .A(_143_),
    .B(\DATA.din[17] ),
    .Y(_151_)
  );
  AO21x1_ASAP7_75t_SL _299_ (
    .A1(dout[17]),
    .A2(_150_),
    .B(_151_),
    .Y(_092_)
  );
  AND2x2_ASAP7_75t_SL _300_ (
    .A(_143_),
    .B(\DATA.din[18] ),
    .Y(_152_)
  );
  AO21x1_ASAP7_75t_SL _301_ (
    .A1(dout[18]),
    .A2(_150_),
    .B(_152_),
    .Y(_093_)
  );
  AND2x2_ASAP7_75t_SL _302_ (
    .A(_143_),
    .B(\DATA.din[19] ),
    .Y(_153_)
  );
  AO21x1_ASAP7_75t_SL _303_ (
    .A1(dout[19]),
    .A2(_150_),
    .B(_153_),
    .Y(_094_)
  );
  AND2x2_ASAP7_75t_SL _304_ (
    .A(_143_),
    .B(\DATA.din[20] ),
    .Y(_154_)
  );
  AO21x1_ASAP7_75t_SL _305_ (
    .A1(dout[20]),
    .A2(_150_),
    .B(_154_),
    .Y(_095_)
  );
  BUFx2_ASAP7_75t_SL _306_ (
    .A(load),
    .Y(_155_)
  );
  AND2x2_ASAP7_75t_SL _307_ (
    .A(_155_),
    .B(\DATA.din[21] ),
    .Y(_156_)
  );
  AO21x1_ASAP7_75t_SL _308_ (
    .A1(dout[21]),
    .A2(_150_),
    .B(_156_),
    .Y(_096_)
  );
  AND2x2_ASAP7_75t_SL _309_ (
    .A(_155_),
    .B(\DATA.din[22] ),
    .Y(_157_)
  );
  AO21x1_ASAP7_75t_SL _310_ (
    .A1(dout[22]),
    .A2(_150_),
    .B(_157_),
    .Y(_097_)
  );
  AND2x2_ASAP7_75t_SL _311_ (
    .A(_155_),
    .B(\DATA.din[23] ),
    .Y(_158_)
  );
  AO21x1_ASAP7_75t_SL _312_ (
    .A1(dout[23]),
    .A2(_150_),
    .B(_158_),
    .Y(_098_)
  );
  AND2x2_ASAP7_75t_SL _313_ (
    .A(_155_),
    .B(\DATA.din[24] ),
    .Y(_159_)
  );
  AO21x1_ASAP7_75t_SL _314_ (
    .A1(dout[24]),
    .A2(_150_),
    .B(_159_),
    .Y(_099_)
  );
  AND2x2_ASAP7_75t_SL _315_ (
    .A(_155_),
    .B(\DATA.din[25] ),
    .Y(_160_)
  );
  AO21x1_ASAP7_75t_SL _316_ (
    .A1(dout[25]),
    .A2(_150_),
    .B(_160_),
    .Y(_100_)
  );
  AND2x2_ASAP7_75t_SL _317_ (
    .A(_155_),
    .B(\DATA.din[26] ),
    .Y(_161_)
  );
  AO21x1_ASAP7_75t_SL _318_ (
    .A1(dout[26]),
    .A2(_150_),
    .B(_161_),
    .Y(_101_)
  );
  AND2x2_ASAP7_75t_SL _319_ (
    .A(_155_),
    .B(\DATA.din[27] ),
    .Y(_162_)
  );
  AO21x1_ASAP7_75t_SL _320_ (
    .A1(dout[27]),
    .A2(_128_),
    .B(_162_),
    .Y(_102_)
  );
  AND2x2_ASAP7_75t_SL _321_ (
    .A(_155_),
    .B(\DATA.din[28] ),
    .Y(_163_)
  );
  AO21x1_ASAP7_75t_SL _322_ (
    .A1(dout[28]),
    .A2(_128_),
    .B(_163_),
    .Y(_103_)
  );
  AND2x2_ASAP7_75t_SL _323_ (
    .A(_155_),
    .B(\DATA.din[29] ),
    .Y(_164_)
  );
  AO21x1_ASAP7_75t_SL _324_ (
    .A1(dout[29]),
    .A2(_128_),
    .B(_164_),
    .Y(_104_)
  );
  AND2x2_ASAP7_75t_SL _325_ (
    .A(_155_),
    .B(\DATA.din[30] ),
    .Y(_165_)
  );
  AO21x1_ASAP7_75t_SL _326_ (
    .A1(dout[30]),
    .A2(_128_),
    .B(_165_),
    .Y(_105_)
  );
  AND2x2_ASAP7_75t_SL _327_ (
    .A(load),
    .B(\DATA.din[31] ),
    .Y(_166_)
  );
  AO21x1_ASAP7_75t_SL _328_ (
    .A1(dout[31]),
    .A2(_128_),
    .B(_166_),
    .Y(_106_)
  );
  AND2x2_ASAP7_75t_SL _329_ (
    .A(_110_),
    .B(_129_),
    .Y(_070_)
  );
  XOR2x2_ASAP7_75t_SL _330_ (
    .A(_068_),
    .B(_110_),
    .Y(_167_)
  );
  AND2x2_ASAP7_75t_SL _331_ (
    .A(_129_),
    .B(_167_),
    .Y(_071_)
  );
  AO21x1_ASAP7_75t_SL _332_ (
    .A1(_113_),
    .A2(_111_),
    .B(_116_),
    .Y(_168_)
  );
  AND3x1_ASAP7_75t_SL _333_ (
    .A(_128_),
    .B(_121_),
    .C(_168_),
    .Y(_072_)
  );
  XNOR2x2_ASAP7_75t_SL _334_ (
    .A(_122_),
    .B(_121_),
    .Y(_169_)
  );
  AND2x2_ASAP7_75t_SL _335_ (
    .A(_129_),
    .B(_169_),
    .Y(_073_)
  );
  OAI21x1_ASAP7_75t_SL _336_ (
    .A1(_108_),
    .A2(_121_),
    .B(_107_),
    .Y(_170_)
  );
  AND3x2_ASAP7_75t_SL _337_ (
    .A(_128_),
    .B(_031_),
    .C(_170_),
    .Y(_074_)
  );
  DLLx1_ASAP7_75t_SL _338_ (
    .CLK(_013_),
    .D(\DEMUX16X4.d_in ),
    .Q(\DATA.din[13] )
  );
  DLLx1_ASAP7_75t_SL _339_ (
    .CLK(_004_),
    .D(\DEMUX16X4.d_in ),
    .Q(\DATA.din[4] )
  );
  DLLx1_ASAP7_75t_SL _340_ (
    .CLK(_010_),
    .D(\DEMUX16X4.d_in ),
    .Q(\DATA.din[10] )
  );
  DLLx1_ASAP7_75t_SL _341_ (
    .CLK(_023_),
    .D(\DEMUX16X4.d_in ),
    .Q(\DATA.din[23] )
  );
  DLLx1_ASAP7_75t_SL _342_ (
    .CLK(_003_),
    .D(\DEMUX16X4.d_in ),
    .Q(\DATA.din[3] )
  );
  DLLx1_ASAP7_75t_SL _343_ (
    .CLK(_014_),
    .D(\DEMUX16X4.d_in ),
    .Q(\DATA.din[14] )
  );
  DLLx1_ASAP7_75t_SL _344_ (
    .CLK(_019_),
    .D(\DEMUX16X4.d_in ),
    .Q(\DATA.din[19] )
  );
  DLLx1_ASAP7_75t_SL _345_ (
    .CLK(_002_),
    .D(\DEMUX16X4.d_in ),
    .Q(\DATA.din[2] )
  );
  DLLx1_ASAP7_75t_SL _346_ (
    .CLK(_024_),
    .D(\DEMUX16X4.d_in ),
    .Q(\DATA.din[24] )
  );
  DLLx1_ASAP7_75t_SL _347_ (
    .CLK(_009_),
    .D(\DEMUX16X4.d_in ),
    .Q(\DATA.din[9] )
  );
  DLLx1_ASAP7_75t_SL _348_ (
    .CLK(_001_),
    .D(\DEMUX16X4.d_in ),
    .Q(\DATA.din[1] )
  );
  DLLx1_ASAP7_75t_SL _349_ (
    .CLK(_017_),
    .D(\DEMUX16X4.d_in ),
    .Q(\DATA.din[17] )
  );
  DLLx1_ASAP7_75t_SL _350_ (
    .CLK(_025_),
    .D(\DEMUX16X4.d_in ),
    .Q(\DATA.din[25] )
  );
  DLLx1_ASAP7_75t_SL _351_ (
    .CLK(_000_),
    .D(\DEMUX16X4.d_in ),
    .Q(\DATA.din[0] )
  );
  DLLx1_ASAP7_75t_SL _352_ (
    .CLK(_012_),
    .D(\DEMUX16X4.d_in ),
    .Q(\DATA.din[12] )
  );
  DLLx1_ASAP7_75t_SL _353_ (
    .CLK(_008_),
    .D(\DEMUX16X4.d_in ),
    .Q(\DATA.din[8] )
  );
  DLLx1_ASAP7_75t_SL _354_ (
    .CLK(_026_),
    .D(\DEMUX16X4.d_in ),
    .Q(\DATA.din[26] )
  );
  DLLx1_ASAP7_75t_SL _355_ (
    .CLK(_020_),
    .D(\DEMUX16X4.d_in ),
    .Q(\DATA.din[20] )
  );
  DLLx1_ASAP7_75t_SL _356_ (
    .CLK(_016_),
    .D(\DEMUX16X4.d_in ),
    .Q(\DATA.din[16] )
  );
  DLLx1_ASAP7_75t_SL _357_ (
    .CLK(_027_),
    .D(\DEMUX16X4.d_in ),
    .Q(\DATA.din[27] )
  );
  DLLx1_ASAP7_75t_SL _358_ (
    .CLK(_007_),
    .D(\DEMUX16X4.d_in ),
    .Q(\DATA.din[7] )
  );
  DLLx1_ASAP7_75t_SL _359_ (
    .CLK(_015_),
    .D(\DEMUX16X4.d_in ),
    .Q(\DATA.din[15] )
  );
  DLLx1_ASAP7_75t_SL _360_ (
    .CLK(_028_),
    .D(\DEMUX16X4.d_in ),
    .Q(\DATA.din[28] )
  );
  DLLx1_ASAP7_75t_SL _361_ (
    .CLK(_021_),
    .D(\DEMUX16X4.d_in ),
    .Q(\DATA.din[21] )
  );
  DLLx1_ASAP7_75t_SL _362_ (
    .CLK(_006_),
    .D(\DEMUX16X4.d_in ),
    .Q(\DATA.din[6] )
  );
  DLLx1_ASAP7_75t_SL _363_ (
    .CLK(_029_),
    .D(\DEMUX16X4.d_in ),
    .Q(\DATA.din[29] )
  );
  DLLx1_ASAP7_75t_SL _364_ (
    .CLK(_011_),
    .D(\DEMUX16X4.d_in ),
    .Q(\DATA.din[11] )
  );
  DLLx1_ASAP7_75t_SL _365_ (
    .CLK(_018_),
    .D(\DEMUX16X4.d_in ),
    .Q(\DATA.din[18] )
  );
  DLLx1_ASAP7_75t_SL _366_ (
    .CLK(_030_),
    .D(\DEMUX16X4.d_in ),
    .Q(\DATA.din[30] )
  );
  DLLx1_ASAP7_75t_SL _367_ (
    .CLK(_005_),
    .D(\DEMUX16X4.d_in ),
    .Q(\DATA.din[5] )
  );
  DLLx1_ASAP7_75t_SL _368_ (
    .CLK(_022_),
    .D(\DEMUX16X4.d_in ),
    .Q(\DATA.din[22] )
  );
  DLLx1_ASAP7_75t_SL _369_ (
    .CLK(_031_),
    .D(\DEMUX16X4.d_in ),
    .Q(\DATA.din[31] )
  );
  DFFLQNx1_ASAP7_75t_SL _370_ (
    .CLK(_069_),
    .D(_070_),
    .QN(_033_)
  );
  DFFLQNx1_ASAP7_75t_SL _371_ (
    .CLK(_069_),
    .D(_071_),
    .QN(_068_)
  );
  DFFLQNx1_ASAP7_75t_SL _372_ (
    .CLK(_069_),
    .D(_072_),
    .QN(_067_)
  );
  DFFLQNx1_ASAP7_75t_SL _373_ (
    .CLK(_069_),
    .D(_073_),
    .QN(_066_)
  );
  DFFLQNx1_ASAP7_75t_SL _374_ (
    .CLK(_069_),
    .D(_074_),
    .QN(_032_)
  );
  DFFLQNx1_ASAP7_75t_SL _375_ (
    .CLK(_069_),
    .D(_075_),
    .QN(_065_)
  );
  DFFLQNx1_ASAP7_75t_SL _376_ (
    .CLK(_069_),
    .D(_076_),
    .QN(_064_)
  );
  DFFLQNx1_ASAP7_75t_SL _377_ (
    .CLK(_069_),
    .D(_077_),
    .QN(_063_)
  );
  DFFLQNx1_ASAP7_75t_SL _378_ (
    .CLK(_069_),
    .D(_078_),
    .QN(_062_)
  );
  DFFLQNx1_ASAP7_75t_SL _379_ (
    .CLK(_069_),
    .D(_079_),
    .QN(_061_)
  );
  DFFLQNx1_ASAP7_75t_SL _380_ (
    .CLK(_069_),
    .D(_080_),
    .QN(_060_)
  );
  DFFLQNx1_ASAP7_75t_SL _381_ (
    .CLK(_069_),
    .D(_081_),
    .QN(_059_)
  );
  DFFLQNx1_ASAP7_75t_SL _382_ (
    .CLK(_069_),
    .D(_082_),
    .QN(_058_)
  );
  DFFLQNx1_ASAP7_75t_SL _383_ (
    .CLK(_069_),
    .D(_083_),
    .QN(_057_)
  );
  DFFLQNx1_ASAP7_75t_SL _384_ (
    .CLK(_069_),
    .D(_084_),
    .QN(_056_)
  );
  DFFLQNx1_ASAP7_75t_SL _385_ (
    .CLK(_069_),
    .D(_085_),
    .QN(_055_)
  );
  DFFLQNx1_ASAP7_75t_SL _386_ (
    .CLK(_069_),
    .D(_086_),
    .QN(_054_)
  );
  DFFLQNx1_ASAP7_75t_SL _387_ (
    .CLK(_069_),
    .D(_087_),
    .QN(_053_)
  );
  DFFLQNx1_ASAP7_75t_SL _388_ (
    .CLK(_069_),
    .D(_088_),
    .QN(_052_)
  );
  DFFLQNx1_ASAP7_75t_SL _389_ (
    .CLK(_069_),
    .D(_089_),
    .QN(_051_)
  );
  DFFLQNx1_ASAP7_75t_SL _390_ (
    .CLK(_069_),
    .D(_090_),
    .QN(_050_)
  );
  DFFLQNx1_ASAP7_75t_SL _391_ (
    .CLK(_069_),
    .D(_091_),
    .QN(_049_)
  );
  DFFLQNx1_ASAP7_75t_SL _392_ (
    .CLK(_069_),
    .D(_092_),
    .QN(_048_)
  );
  DFFLQNx1_ASAP7_75t_SL _393_ (
    .CLK(_069_),
    .D(_093_),
    .QN(_047_)
  );
  DFFLQNx1_ASAP7_75t_SL _394_ (
    .CLK(_069_),
    .D(_094_),
    .QN(_046_)
  );
  DFFLQNx1_ASAP7_75t_SL _395_ (
    .CLK(_069_),
    .D(_095_),
    .QN(_045_)
  );
  DFFLQNx1_ASAP7_75t_SL _396_ (
    .CLK(_069_),
    .D(_096_),
    .QN(_044_)
  );
  DFFLQNx1_ASAP7_75t_SL _397_ (
    .CLK(_069_),
    .D(_097_),
    .QN(_043_)
  );
  DFFLQNx1_ASAP7_75t_SL _398_ (
    .CLK(_069_),
    .D(_098_),
    .QN(_042_)
  );
  DFFLQNx1_ASAP7_75t_SL _399_ (
    .CLK(_069_),
    .D(_099_),
    .QN(_041_)
  );
  DFFLQNx1_ASAP7_75t_SL _400_ (
    .CLK(_069_),
    .D(_100_),
    .QN(_040_)
  );
  DFFLQNx1_ASAP7_75t_SL _401_ (
    .CLK(_069_),
    .D(_101_),
    .QN(_039_)
  );
  DFFLQNx1_ASAP7_75t_SL _402_ (
    .CLK(_069_),
    .D(_102_),
    .QN(_038_)
  );
  DFFLQNx1_ASAP7_75t_SL _403_ (
    .CLK(_069_),
    .D(_103_),
    .QN(_037_)
  );
  DFFLQNx1_ASAP7_75t_SL _404_ (
    .CLK(_069_),
    .D(_104_),
    .QN(_036_)
  );
  DFFLQNx1_ASAP7_75t_SL _405_ (
    .CLK(_069_),
    .D(_105_),
    .QN(_035_)
  );
  DFFLQNx1_ASAP7_75t_SL _406_ (
    .CLK(_069_),
    .D(_106_),
    .QN(_034_)
  );
endmodule
